### ISSUE TITLE
Medication list

### ISSUE THREAD

**Issue by anniviz** [anniviz/capstone-project#1]
## Value statement - a requirement, not a solution
As a **user** 
I need **to see my medication list** 
so that **I can take the right medicine** 

## Description (Text, Scribble, Wireframe, Design)

![med-list](https://user-images.githubusercontent.com/55999008/120552098-12855b00-c3f7-11eb-8455-e1619371403e.png)

## Acceptance criteria
- [x] A set of cards is rendered (a hard coded array is the basis)
- [x] Cards are sorted time ascending
- [x] The header shows the system date

## Tasks
- [x] Feature branch
- [x] Example array
- [x] Card component w/ storybook and test
- [x] Header component w/ storybook and test
- [x] Add components to App with logic

## Complexity 
low
