### ISSUE TITLE
List of observations

### ISSUE THREAD

**Issue by anniviz** [anniviz/capstone-project#13]
## Value statement - a requirement, not a solution
As a **user** 
I need **to see what my vital signs are / have been** 
so that **I can keep track of them and show them to my doctor** 

## Description (Text, Scribble, Wireframe, Design)

![Observations – user story](https://user-images.githubusercontent.com/55999008/121870565-79faaf00-cd03-11eb-8a26-27a10bf642ba.png)

## Acceptance criteria
- [x] A set of vital signs is rendered
- [x] The obbservations are sorted alphabetically (Notizen (notes) are always first)
- [x] The user can switch pages in a navigation bar

## Tasks
- [x] Feature branch
- [x] Example array
- [x] Observation component w/ storybook and tests
- [x] Navigation component w/ storybook and tests
- [x] Add components to App with logic

## Complexity 
low
