### ISSUE TITLE
Observations form

### ISSUE THREAD

**Issue by anniviz** [anniviz/capstone-project#14]
## Value statement - a requirement, not a solution
As a **user** 
I need **add my own observations** 
so that **I can keep track of my actual vital signs** 

## Description (Text, Scribble, Wireframe, Design)

![Observations – user story form](https://user-images.githubusercontent.com/55999008/121871465-6f8ce500-cd04-11eb-992d-9b95087b2f81.png)

## Acceptance criteria
- [x] Header shows selected date
- [x] User can select from a (predefined) dropdown menu which observation he wants to track
- [x] There is a menu item for notes (Notizen)
- [x] Time is prefilled with current time but can be changed by the user

## Tasks
- [x] Feature branch
- [x] Create drop down component w/ storybook and tests
- [x] Create form page for observations w/storybook and tests

## Complexity 
(low, medium, high)
