### ISSUE TITLE
history

### ISSUE THREAD

**Issue by anniviz** [anniviz/capstone-project#16]
## Value statement - a requirement, not a solution
As a **user** 
I need **to get my medications automated** 
so that **I don't need to type in my medication every day** 

## Description (Text, Scribble, Wireframe, Design)
When the user opens the app on a new day, the medications for the day will be prefilled (the same like it was the day before). This happens also for the days in between, when the user doesn't open the app for several days.

## Acceptance criteria
- [ ] First entry on the day the app was first used by the user
- [ ] Every day there will be a new medication plan (generated from the plan of the day before)
- [ ] On days where the app is not used there is a medication plan (all cards are marked as not done)
- [ ] The last saved version of the plan will be saved for the day

## Tasks
- [ ] Feature branch
- [ ] Create functionality to set medications automatically

## Complexity 
high
