### ISSUE TITLE
Copy day

### ISSUE THREAD

**Issue by anniviz** [anniviz/capstone-project#19]
## Value statement - a requirement, not a solution
As a **user** 
I need **to copy the medication list of a whole day** 
so that **don't have to type in the medications each day** 

## Description (Text, Scribble, Wireframe, Design)

![Copy day](https://user-images.githubusercontent.com/55999008/122743838-aeccb000-d287-11eb-96c0-07e51bdf3b55.png)
![Copy day – 1](https://user-images.githubusercontent.com/55999008/122743844-b1c7a080-d287-11eb-9890-7392540c692d.png)

## Acceptance criteria
- [x] After clicking the edit icon there is the option to copy the day (Tag kopieren)
- [x] In a calendar the user can select the day he wants to copy the medication list for the whole day 
- [x] After clicking "kopieren" all medications are saved in the medicationsDiary, if there was already a medication for that day it will be overwritten

## Tasks
- [x] Feature branch
- [x] Update App with components and logic
- [x] Update storybook and tests

## Complexity 
low
