### ISSUE TITLE
Medication card form

### ISSUE THREAD

**Issue by anniviz** [anniviz/capstone-project#2]
## Value statement - a requirement, not a solution
As a **user** 
I need **to create a medication card** 
so that **I can add my personal medication** 

## Description (Text, Scribble, Wireframe, Design)

![med-form-1](https://user-images.githubusercontent.com/55999008/121001771-e9b0ed00-c78b-11eb-97ca-2c2a361e027b.png)
![med-form-2](https://user-images.githubusercontent.com/55999008/121001777-eb7ab080-c78b-11eb-81dc-a80bf83d0869.png)
![med-form-3](https://user-images.githubusercontent.com/55999008/121001783-ecabdd80-c78b-11eb-9aab-61d9f3617363.png)

## Acceptance criteria
- [x] Save data to local storage
- [x] when there is no content for the main page, this is the first screen
- [x] "zurück" button brings you back to main page and empties the form
- [x] "erstellen" button is disabled until there is content for the main page
- [x] "Hinzufügen" (start page) is fixed at the top of the screen (and not pushed down by cards)
- [x] The url does not change

## Tasks
- [x] Feature branch
- [x] Component for "Zurück" ???
- [x] Form component w/ storybook and test
- [x] Button component w/ storybook and test
- [x] Update App with components and logic
- [x] Add localStorage

## Complexity 
medium
