### ISSUE TITLE
Edit observation

### ISSUE THREAD

**Issue by anniviz** [anniviz/capstone-project#27]
## Value statement - a requirement, not a solution
As a **user** 
I need **to edit my observation** 
so that **I can correct myself if I saved something wrong** 

## Description (Text, Scribble, Wireframe, Design)

same design like in the medication group

## Acceptance criteria
- [ ] After click on the edit icon the icon changes to back icon is visible and every observation has an icon for edit and delete
- [ ] After click on the back icon the edit mode is closed
- [ ] After click on the delete icon the observation is deleted
- [ ] After click on the edit icon the matching form will be shown
- [ ] The form is prefilled with the time and value from the observation the user wants to edit
- [ ] After click on"zurück" (back) (in the form) the observations page is shown and the observation is not edited
- [ ] After click on "speichern" (save) the observations page is shown and the card is updated (on the screen and in local storage)

## Tasks
- [ ] Feature branch
- [ ] Update App with components and logic
- [ ] Update tests

## Complexity 
medium
