### ISSUE TITLE
Delete medication card

### ISSUE THREAD

**Issue by anniviz** [anniviz/capstone-project#3]
## Value statement - a requirement, not a solution
As a **user** 
I need **to delete a medication card** 
so that **I don't see medication I don't need anymore** 

## Description (Text, Scribble, Wireframe, Design)

![delete-med-card](https://user-images.githubusercontent.com/55999008/120556216-7bbb9d00-c3fc-11eb-9d89-995cf8e995a7.png)

## Acceptance criteria
- [x] By hitting the '-' button the card will be deleted (on the screen and local storage)
- [x] After deleting the last card the form is the active screen 

## Tasks
- [x] Feature branch
- [x] '-' button component w/ storybook and tests
- [x] Update App with components and logic

## Complexity 
low
