### ISSUE TITLE
Edit medication card

### ISSUE THREAD

**Issue by anniviz** [anniviz/capstone-project#4]
## Value statement - a requirement, not a solution
As a **user** 
I need **to edit my medication** 
so that **I can always see my current medication** 

## Description (Text, Scribble, Wireframe, Design)

![edit-med-card-1](https://user-images.githubusercontent.com/55999008/121521984-f4ba8600-c9f4-11eb-8d47-df56466bd6f7.png)
![edit-med-card-2](https://user-images.githubusercontent.com/55999008/121521998-f71ce000-c9f4-11eb-8562-0760786e9588.png)
![edit-med-card-3](https://user-images.githubusercontent.com/55999008/121522006-f84e0d00-c9f4-11eb-9ef3-134abb3a2330.png)

## Acceptance criteria
- [x] After click on "Bearbeiten" (edit) "Hinzufügen" (add) is hidden, "Abbrechen" (cancel) is visible and the user can choose a card which he wants to edit
- [x] After click on "Abbbrechen" (cancel) the normal main page is shown
- [x] After clicking the card that the user wants to edit the form will be shown
- [x] The form is prefilled with the text from the card the user wants to edit
- [x] After clicking the "löschen" (delete) button the form will be cleared out, the placeholder text will be shown and the focus is on the time text field
- [x] After click on"zurück" (back) the main page is shown (with "Hinzufügen" and "Bearbeiten") and the card is not edited
- [x] After click on "speichern" (save) the main page is shown and the card is updated (on the screen and in local storage)

## Tasks
- [x] Feature branch
- [x] Update App with components and logic
- [x] Update tests

## Complexity 
medium
