### ISSUE TITLE
Mark medication as done

### ISSUE THREAD

**Issue by anniviz** [anniviz/capstone-project#5]
## Value statement - a requirement, not a solution
As a **user** 
I need **to mark my medication as done** 
so that **I can see which medicine I have to take** 

## Description (Text, Scribble, Wireframe, Design)

![mark-as-done-1](https://user-images.githubusercontent.com/55999008/120607281-52c4f780-c450-11eb-87d9-befac5a567de.png)

![mark-as-done-2](https://user-images.githubusercontent.com/55999008/120607303-58bad880-c450-11eb-802b-eecdf87f9305.png)

![Medication List](https://user-images.githubusercontent.com/55999008/121869908-cbef0500-cd02-11eb-83a7-87eb88051599.png)

## Acceptance criteria
- [x] After clicking the check button it will turn green
- [x] The status of the check will be stored in the data
- [x] All check buttons are reset when the list of medications in copied into another day 

## Tasks
- [x] Feature branch
- [x] Create done component w/ storybook and tests
- [x] Update App with components and logic

## Complexity 
low
