### ISSUE TITLE
Calendar

### ISSUE THREAD

**Issue by anniviz** [anniviz/capstone-project#6]
## Value statement - a requirement, not a solution
As a **user** 
I need **be able to see switch days in a calendar** 
so that **I can see my medication on specific days** 

## Description (Text, Scribble, Wireframe, Design)

![history](https://user-images.githubusercontent.com/55999008/120616785-cddedb80-c459-11eb-927e-a01a6bc20764.png)

## Acceptance criteria
- [x] The user can switch days in a calendar
- [x] Plans in the past can be edited 
- [x] Selected date is shown in header

## Tasks
- [x] Feature branch
- [x] Calendar component (from dependency)
- [x] Set up new data format
- [x] Update App with components and logic

## Complexity 
high
